### ISSUE TITLE
Feature Request: Overlays for all modal-like builders

### ISSUE THREAD

**Issue by huntabyte** [melt-ui/melt-ui#1023]
Currently, we have components like the Menus, Combobox, Select, etc. that act similar to modals by default in the sense that they prevent scroll when open, close on escape, and close on outside clicks. What these don't do however is prevent and disable interactions outside of the menu/content.

For example, here's the currently default behavior of the Select:

https://github.com/melt-ui/melt-ui/assets/64506580/5dbc203f-2bbb-4a16-b17e-571666bce687

Since the scroll is disabled, it appears as though I shouldn't be able to do anything outside the content, but I can still interact with things outside of the "modal", which creates this weird in-between of "I can interact with things only within the current viewport", which feels a bit sloppy.

Perhaps the simplest way to solve this problem would be to add an additional `overlay` element to the various builders where we support modal behaviors, similar to the dialog. This wouldn't be a breaking change and opting out would be as simple as not using the overlay.

This could be handled by the user manually today, but only if they are using `forceVisible` and can stick the overlay behind the synced `open` state, so I think adding a 1st party element would be beneficial.

**Comment by silenceofthewans** [comment]
This will definitely solve my use case of using `Select`, `Combobox` and basically all builders with `positioning` inside a bottom sheet since it is more consistent and scalable in terms of displaying options between mobile and desktop. Currently, because of no overlay I use a dialog and add my sheet logic component inside the `content` which further has a slot for actual sheet content. So, the flow is like `Combobox -> Drawer (For Overlay) -> Sheet (Actual Draggable Part)`. Combobox uses `positioning: null` and Drawer uses `$open` store from combobox for it's state and and the sheet. Even though there is no separate `$trigger` element for Combobox like Select. I made it work by just adding $input on `<Button/>` 🤷‍♂️ but this will be solved by #1014 when we could actually affect the $open state so only overlay was missing and by adding an overlay element I could simplify it like: `Combobox (With Overlay) -> Sheet ($menu inside)`

**Comment by TGlide** [comment]
As said in #1035, I think a `modal` prop is better. An overlay for menus and a popover just doesn't seem right 🤔
