### ISSUE TITLE
🌟Feature request: Back button

### ISSUE THREAD

**Issue by maarekj** [melt-ui/melt-ui#1027]
**Is your feature request related to a problem? Please describe.**

​I have a problem with the dialog component on mobile.

On mobile (at least on Android), users are used to using the back key to go back in navigation.
With the dialog open in full screen, the user who presses the go back key will return to the previous page, although he expects this action to close the dialog.

**Describe the solution you'd like**

The "go back" key should be used to close the modal. (Same as the escape key).

For this, we could add a "closeOnBackKey" option (like "closeOnEscape")

**Additional context**

I tried to implement this on the user side, but there is no simple way to intercept the return key, to do this you have to create an entry in the browser history etc. And it's hard to keep that in sync with the "open" state.

**Comment by lumosminima** [comment]
If by "go back" key you meant the gesture-based back navigation/global back button then that will only be possible through `pushState` and `replaceState` browser APIs since there is no "back" event in browser currently only a `popstate` event which fires any time you go forward or back in history. So, you are looking for sveltekit's [shallow routing](https://kit.svelte.dev/docs/shallow-routing) and here is the [melt example repo](https://github.com/melt-ui/examples/tree/main/dialog-shallow-routing) in which it is applied to a melt dialog which is able to close using the "Back" gesture or button, using the [createSync utility](https://melt-ui.com/docs/controlled#syncing-state). It is a good-enough starting point albeit missing some cases like using nested dialogs with shallow routing.

**Comment by maarekj** [comment]
Thanks for your return.

Indeed, when I tried to implement all this, I quickly understood that I had to play with the browser's (or sveltekit) pushState.

But it's not easy to synchronize pushState with store `$open` dialog state. Furthermore, as you say, it does not manage nested dialogs, and in my case I have nested dialogs.
