### ISSUE TITLE
Select component - $Selected gets overridden every time a parent accordion opens/closes 

### ISSUE THREAD

**Issue by federicomarcantognini** [melt-ui/melt-ui#1030]
### Describe the bug

Adding a Select component inside an accordion, the $selected state gets to its 'undefined' state every time the accordion closes/opens, overriding the current selected option.

https://melt-ui.com/docs/builders/select

`const {
  elements: { trigger, menu, option },
  states: { selected, open },
  helpers: { isSelected },
} = createSelect({
  forceVisible: true,
  positioning: {
	  placement: 'bottom',
	  fitViewport: true,
	  sameWidth: false,
  },
  required: true
  multiple: false,
  defaultSelected: {'value': 'one, 'label': 'one', disabled: false},
});`

### Reproduction

https://stackblitz.com/edit/github-vkpcpc?file=src%2Flib%2Fcomponents%2FSelect.svelte

### System Info

```bash
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 1.84 GB / 15.73 GB
  Binaries:
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.4.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (121.0.2277.112)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @melt-ui/svelte: ^0.74.0 => 0.74.0
    @sveltejs/kit: ^1.27.4 => 1.30.3
    svelte: ^4.2.7 => 4.2.8
```

### Severity

blocking an upgrade

**Comment by federicomarcantognini** [comment]
Here you go, click on the first accordion and see that it gets back to 'undefined' every time the first accordion opens/closes: https://stackblitz.com/github/melt-ui/template?file=src%2Froutes%2F%2Bpage.svelte

**Comment by TGlide** [comment]
> Click on the first accordion item and see that the select '$selected' state gets back to its original 'undefined' state every time the first accordion opens/closes: https://stackblitz.com/github/melt-ui/template?file=src%2Froutes%2F%2Bpage.svelte
> 
> There are other issues with the Melt UI select component, but I guess it is better to follow a one-topic-one-issue

You linked to the default Melt template. There's no select there

**Comment by federicomarcantognini** [comment]
Apologies, I replaced the link above

**Comment by huntabyte** [comment]
This isn't Melt UI-specific behavior, this is the expected Svelte behavior.

https://svelte.dev/repl/811fae380bfa480e948a8ccb4f8fa15a?version=4.2.12

When you're calling `createSelect` inside of a component that is conditionally rendered, it will be invoked as new each time the component is mounted (when open).

If you want to persist that state, you need to setup some state (store or otherwise) at a higher level (the `Accordion`) in the case of your example.

Here's a modified version of your repro with the behavior you're looking for: https://stackblitz.com/edit/github-vkpcpc-wk8u1d?file=src%2Flib%2Fcomponents%2FSelect.svelte
