### ISSUE TITLE
🐛Bug: Backspace on Tags Input closes keyboard on mobile

### ISSUE THREAD

**Issue by TGlide** [melt-ui/melt-ui#115]
https://twitter.com/pawelblaszczyk_/status/1674072874167009281

**Comment by geerew** [comment]
Mm. I know why .. 

I designed it that only 1 element is in focus. If a tag is in focus, then the input goes out of focus.

When you hit backspace and are at position 0 on the input, the last tag is selected , gets focus and the input looses forcus

Zag operates differently so this isn’t an issue. The input is always in focus, even when you tab or arrow through tags. Only when you click/tab off the component, does input lose focus.

I could rework it to use this approach. It’s a big change but happy to do it if you prefer input always in focus …?

**Comment by TGlide** [comment]
@geerew we could do that, or have backspace delete the last input instead of focusing on it. Need to see if there's any accessibility concerns with that though.

**Comment by geerew** [comment]
I wouldn’t be happy with that approach, as you could accidentally delete a tag. 

The approach now is such that when you hit backspace the last tag is set as selected and if you were to hit backspace again, then it would be deleted. 

To be honest, always having the input be in focus solves a lot of problems with the features that I want to add such as Blur and it kind of makes sense that you can always type a new tag, even if other types are selected. As it stands now, there isn’t even a point in selecting a tag because I haven’t implemented the tag edit feature yet. 

If you are happy with it, I think I will go ahead and make it that input is always in focus ..?
