### ISSUE TITLE
css variables to Popover component blocked

### ISSUE THREAD

**Issue by eranmiller** [melt-ui/melt-ui#1166]
### Describe the bug

**Expected** to be able to forward css variables through Popover component
**Currently** css variables aren't forwarded when "use:melt=$content" is present
**Note** the link demonstrates two Popover components, one properly employing use:melt={$context} and the other without the action.  The one without predictably breaks popover built-in css, yet no longer blocks passing css --bgcolor variable.

Thomas G. Lopes — 04/04/2024 5:23 PM
And yes, I can see why style would not work... We pass our own style attributes, but this is definitely something that should be improved. Would you mind creating a GH issue?

### Reproduction

https://www.sveltelab.dev/93z7nu6ubl5kity

### System Info

```bash
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.3 - /usr/local/bin/pnpm
  npmPackages:
    @melt-ui/svelte: ^0.76.3 => 0.76.3 
    @sveltejs/kit: ^2.0.0 => 2.5.5 
    svelte: ^4.0.5 => 4.2.12
```

### Severity

annoyance

**Comment by anatolzak** [comment]
@eranmiller I noticed that in your repro, you actually mentioned another bug. I created a separate issue here https://github.com/melt-ui/melt-ui/issues/1167 which is solved by PR https://github.com/melt-ui/melt-ui/pull/1080

**Comment by anatolzak** [comment]
According to the [Svelte docs](https://svelte.dev/docs/component-directives#style-props), when passing css variables to components, svelte just creates a wrapper div with the css variables you provided. It doesn't actually "pass" the css variables as inline styles.

This
```svelte
<Slider bind:value min={0} --rail-color="black" --track-color="rgb(0, 0, 255)" />
```
Becomes this
```svelte
<div style="display: contents; --rail-color: black; --track-color: rgb(0, 0, 255)">
	<Slider bind:value min={0} max={100} />
</div>
```

The reason removing `use:melt={$content}` seems to work is because then the popover content is not portalled and therefore is nested within the div svelte created with your css variables.

There is not an actual issue with melt overriding styles. You can pass styles to elements that use melt builders and they work as expected.

```svelte
<button
	use:melt={$trigger}
	style="background-color: red;"
>
	<Plus class="size-4" aria-label="plus" />
</button>

{#if $open}
	<div
		use:melt={$content}
		style="background-color: red;"
	>
		<p>Add item to library</p>
	</div>
{/if}
```

https://github.com/melt-ui/melt-ui/assets/53095479/ee550f4e-db19-4bb7-bf2e-9e87fc348964

**Comment by eranmiller** [comment]
Got it! 
Thank you, your attention and explanation are appreciated.
