### ISSUE TITLE
🐛Bug: Selecting a Combobox item closes the parent Dialog

### ISSUE THREAD

**Issue by szymondlugolecki** [melt-ui/melt-ui#189]
**Describe the bug**
Selecting an item in the Combobox in the setting shown below unintentionally closes the Dialog.
```html
<Dialog>
  <Combobox />
</Dialog>
```
The problem only occurs with mouse selection, it works properly with keyboard navigation

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 114.0.5735.199

**Comment by huntabyte** [comment]
Thanks for taking the time to open up an issue @szymondlugolecki !

As @TGlide hinted at in the Discord, this is because the Combobox and Dialog portals target the body, so they end up being siblings in the DOM rather than the Combobox being a descendent of the Dialog.  The Combobox may visually appear to be "inside" the Dialog,  but from the DOMs perspective, it is outside, so it's triggering the Dialog's `clickOutside` action.

I think this use case is common and something we should be able to handle from the lib side with no changes to the APIs. It's getting late and I can't look into the specifics at this moment, but here's a rough idea that comes to mind:

For the elements that portal, we could add a `data-melt-portal` attribute, and then before we call the `usePortal` action on any element, we can look for the closest ancestor with a `data-melt-portal`. If they have an ancestor with that attribute, rather than targeting the `body` for that element's portal, we target the closest portal ancestor. This would ensure it's a descendant in the DOM when both are open to squash that `clickOutside` issue. If no ancestor portal element is found, we default to the body per usual.

We'd probably need to use something stable like an `id` to identify the "parent portal" within the initialization of the action and track its ID via an attribute so when the parent moves in the DOM when open, we still have the right element we should portal the descendent to when it opens.

Again, a rough explanation but I'd love to hear feedback/thoughts from others on this approach!

I should have some free time tomorrow afternoon to tackle this.

**Comment by TGlide** [comment]
> Thanks for taking the time to open up an issue, @szymondlugolecki!
> 
> As @TGlide hinted at in the Discord, this is because the Combobox and Dialog portals target the body, so they end up being siblings in the DOM rather than the Combobox being a descendent of the Dialog. The Combobox may visually appear to be "inside" the Dialog, but from the DOMs perspective, it is outside, triggering the Dialog's `clickOutside` action.
> 
> This use case is typical and something we should be able to handle from the lib side with no changes to the APIs. It's getting late, and I can't look into the specifics at this moment, but here's a rough idea that comes to mind:
> 
> For the elements that portal, we could add a `data-melt-portal` attribute, and then before we call the `usePortal` action on any element, we can look for the closest ancestor with a `data-melt-portal`. If they have an ancestor with that attribute, we target the closest portal ancestor instead of targeting the `body` for that element. This would ensure it's a descendant in the DOM when both are open to squash that `clickOutside` issue. If no ancestor portal element is found, we default to the body per usual.
> 
> We'd probably need to use something stable like an `id` to identify the "parent portal" within the initialization of the action and track its ID via an attribute so when the parent moves in the DOM when open, we still have the right element we should portal the descendent to when it opens.
> 
> Again, a rough explanation, but I'd love to hear feedback/thoughts from others on this approach!
> 
> I should have some free time tomorrow afternoon to tackle this.

I really like this idea!

**Comment by huntabyte** [comment]
Closed by #234
