### ISSUE TITLE
🐛Bug: `[aria-*] attributes do not match their roles` in docs page for lighthouse report

### ISSUE THREAD

**Issue by bennymi** [melt-ui/melt-ui#248]
**Describe the bug**

Hey, I'm getting these warnings for the switch elements when running the lighthouse report on any docs page:

![image](https://github.com/melt-ui/melt-ui/assets/20195536/b41a4061-205f-41ba-9456-c68e6d586aa2)

**Comment by TGlide** [comment]
I got them too! Which is annoying considering Lighthouse is wrong on this. 

Switch is using the following attributes:
![image](https://github.com/melt-ui/melt-ui/assets/26071571/d31f7f49-69bf-4bd6-83f7-7a7a87c0da6a)

According to [WAI-ARIA](https://w3c.github.io/aria/#switch), `aria-checked` is a required attribute, and both `aria-required` & `aria-labelledby` are inheritted attributes. 

[Axe DevTools ](https://www.deque.com/axe/devtools/) reports no issues on this front either.

This is a bit annoying, because sometimes even Axe reports false problems. It helps me a bit though and forces me to check if it's wrong or not.

Closing!
