### ISSUE TITLE
🐛Bug: Hover Card: Breaks element interactions on mobile displays

### ISSUE THREAD

**Issue by Rosslington** [melt-ui/melt-ui#296]
**Describe the bug**
When using the Hover Card component, I manually open the hover card on mobile displays which works fine. However, something with the imported CSS or logic breaks the element interactions. (i.e. buttons that are normally clickable on a desktop, are no longer clickable on mobile). Devs tools shows the elements as being its original size, but only clicks off to side of the element are detected. Video below.

It's the "use:trigger" snippet that breaks the element interactions.

**To Reproduce**
[StackBlitz](https://stackblitz.com/edit/melt-ui-playground-kgto4l?file=src%2Froutes%2F%2Bpage.svelte)
Load the web preview in a new tab using its url > Turn on Device toolbar using chrome dev tools > Set the dimensions to "iPhone 12 Pro"

**Screenshots**
See Video: https://app.screencast.com/gSQDH2BWzkZWZ

**Comment by huntabyte** [comment]
Thanks for catching it, can confirm this is a bug.

Not able to fix it at this very moment, but describing the fix to myself or whoever can get to it first.

Within the `trigger` action, we're calling `e.preventDefault()` for the touch start event, which is good because we don't want the mobile focus to hit the link, however, this prevents mobile users from even clicking on the link.

So what we need to do is after the `e.preventDefault()`, we need to grab the `currentTarget` from the event and fire a `click` event on it, as again we do want to prevent the default behavior of focusing the trigger, but we want to continue on with clicking it as normal.
