### ISSUE TITLE
🐛Bug: Scroll issues with menu in a sticky header

### ISSUE THREAD

**Issue by abdel-17** [melt-ui/melt-ui#321]
**Describe the bug**
I have a sticky header, so I tried using `scroll-padding-top` to prevent it from covering page elements I'm linking to. Unfortunately, that causes strange behavior with dropdown menus. When I exit a menu in the header, it scrolls to the top of the page suddenly.

**To Reproduce**
1. Go to https://stackblitz.com/edit/github-wgnbi5?file=src%2Froutes%2F%2Bpage.svelte
2. Scroll down to the bottom of the page
3. Click the menu button in the header

**Expected behavior**
The scroll position should remain the same, but instead it scrolls to the top of the page.

**Comment by wesharper** [comment]
Is there a reason that you aren't setting preventScroll to `true`? That seems to accomplish the desired result in the sandbox you linked.

**Comment by wesharper** [comment]
I modified the [sandbox](https://stackblitz.com/edit/github-wgnbi5-aytjui?file=src%2Froutes%2F%2Bpage.svelte) a bit to clarify the issue . The initial example makes it look like the sticky header behavior jumps all the way to the top of the page, which it does in that example. To be specific, it actually "jumps" the scroll position by the scroll padding offset. The modified sandbox more accurately shows this behavior.

**Comment by TGlide** [comment]
Funny thing, it does not happen in Firefox. Will look into it.

**Comment by abdel-17** [comment]
We all love browser-specific bugs, don’t we? I tested it in Chrome, but I’m not sure if I did in Safari.

**Comment by abdel-17** [comment]
Any updates on this issue?

**Comment by TGlide** [comment]
> Any updates on this issue?

Mind-reader, I'm actually trying to solve it now!

**Comment by TGlide** [comment]
@abdel-17 its a hard bug to tackle, tbh. I nailed the piecs of code that cause this issue,which are related to focus, but nothing that should be causing scrolling though.

Another thing I noticed, if you apply the scroll-padding to the body, instead of HTML, the issue is also solved. Would this work in your case?

**Comment by abdel-17** [comment]
That could work. I just copied the implementation from stack overflow. If it works, it’s good for me.

**Comment by TGlide** [comment]
Closing due to proposed fix. If anyone has any issues with this, let me know!

**Comment by linusaarnio** [comment]
Hi @TGlide! I'm experiencing this bug, and in this case applying `scroll-padding` to the body tag instead of html unfortunately isn't feasible. Are there other possible workarounds, or is solving the root cause maybe an option? I would be happy to help if given pointers about those pieces of code that caused the issue (if you still remember it 1,5 years later 😅 ).
