### ISSUE TITLE
🐛Bug: Popover jumps to random location on close when it's parent is relative

### ISSUE THREAD

**Issue by geerew** [melt-ui/melt-ui#34]
**Describe the bug**
When yoy have a trigger and content inside a relative element (ex, div) when the popover closes it jumps to a random position

He is an example -> https://stackblitz.com/edit/node-kumaq4?file=src%2Froutes%2F%2Bpage.svelte

On line 9 I have the `relative` class. If this is removed, there is no issue.

Note: I have increased the out:fade to a big number so you see it. If this is a small number like 200ms, it appears like a flicker

**To Reproduce**
1. Open the stackblitz
2. Open the popover
3. Click outside the popover
4. Remove the `relative` class on line 9
5. Redo steps 2 and 3; no issue

**Expected behavior**
Remain in place during an out:fade, even if the parent is relative

**Screenshots**

**Desktop (please complete the following information):**
- OS: MacOS
- Browser: Firefox, Safari, Chrome

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by TGlide** [comment]
Hmm, since svelte transitions are being used, I wouldn't exactly call this a bug... We portal the popover to the body when it's open. As soon as it stops being open, the portal stops being active, and it enters the normal content flow.

We'd probably have to give an option to force the portal, and content, to be active at all times (with a `forceMount` option). And this way, you'll control the open state or not.

**Comment by geerew** [comment]
I see. So the idea is you can have a transition in but not out? When it closes it should disappear immediately?

**Comment by TGlide** [comment]
> I see. So the idea is you can have a transition in but not out? When it closes it should disappear immediately?

Currently, yes, as a limitation. But with forceMount you probably could have both

**Comment by TGlide** [comment]
Closing in favor of #70
