### ISSUE TITLE
🐛Bug: Controlled popover does not work

### ISSUE THREAD

**Issue by hartwm** [melt-ui/melt-ui#393]
**Describe the bug**
Popover doesn't appear to work when used with outside store

**To Reproduce**
Example REPL
https://svelte.dev/repl/2dc9d2ef19cc4ef49254693ec56fba9b?version=4.2.0

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 12.6.5
 - Browser Chrome
 - Version 114

**Comment by TGlide** [comment]
This is not a case of the controlled behaviour not working, but rather, an expected behaviour stemming from the omission of the `trigger` element.

The popover content needs something to anchor to, in this case, the trigger. Here's your example updated so the behaviour is fixed: https://svelte.dev/repl/b778674dd1784b499bc74f24fa57c497?version=4.2.0
