### ISSUE TITLE
🌟Feature request: Add `aria-label` option for the Slider builder

### ISSUE THREAD

**Issue by f-elix** [melt-ui/melt-ui#437]
Currently, the Slider's aria label is hardcoded to 'Volume'. 

I can override it by adding the attribute after the `{...$thumb()}` on the element itself, but it would be nice if could provide it directly to the builder as an option.

**Comment by huntabyte** [comment]
We definitely shouldn't be applying one in this case.

I don't that having it as an option to pass to the builder would be a great idea since it could be applied directly to the element (once we remove the internal application).

My reasoning for this is that then we'd have to do the same for every builder and possibly additional attributes, which could get messy. Options should be reserved to things we need to use internally for one reason or another IMO, but open to having my mind changed!

**Comment by f-elix** [comment]
Ah I think what you said makes a lot of sense. I'm still new to Melt-UI, so I'm not yet aware of the patterns and convention. Indeed, if no other builder works with `label` options (or other attributes), when it makes sense to keep it that way.

It's still pretty weird to hardcode an `aria-label` by default though.

**Comment by TGlide** [comment]
> It's still pretty weird to hardcode an `aria-label` by default though.

The aria-label should not be there by default, mistake on our end! Will remove it. Closing this issue for the reasons @huntabyte mentioned
