### ISSUE TITLE
🌟Feature request: Add option to focus specific element instead of first element

### ISSUE THREAD

**Issue by AndreasHald** [melt-ui/melt-ui#566]
**Is your feature request related to a problem? Please describe.**
When opening the dropdown menu focus is only moved if the dropdown menu is opened with the keyboard. And then it is moved to the first item.

<img width="265" alt="Screenshot 2023-09-29 at 14 11 59" src="https://github.com/melt-ui/melt-ui/assets/8914722/dbaf234f-3904-43fe-84db-56910c49563e">

In this case I'd prefer to move the focus to the input field, so the user can start filtering immediately

**Describe the solution you'd like**
I'd like more control of how the focus is moved, it could be as simple as a selector passed to the constructor and this selector be used to focus instead of the first element

```js
const context = createDropdownMenu({
        focusTarget: "[data-menu-item-autofocus='true']"
    });
```

**Describe alternatives you've considered**
I've tried manually focusing the intended element when the dropdown menu is opened - I couldn't get it to work though - because if the user opens using keyboard melt internally moves focus.

**Comment by huntabyte** [comment]
Going to be exploring some ideas with this, as I keep finding myself needing this same level of flexibility and control over the focus states when getting into some custom components.

Rather than setting a `focusTarget`, I think having the prop be a function that is called (if provided) before the default focus behavior, which would provide more flexibility and enable us to do the same when the various autofocus elements _close_ as well.

This would enable use to leverage some of the cool things about Svelte like binding to elements.

Ideally we'd also have a way to _fallback_ to the default behavior in the event that the element can't be focused or something else goes wrong in the process, to ensure the a11y goodness.

In this rough idea, if `true` is returned from the function, then the behavior falls back to default, otherwise it skips the autofocusing behavior. Not sure if `true` or `false` would be best here, but my idea was that it may be easier to handle on the lib side as we could do something like:

```ts
const defaults = {
  onOpenFocus: () => true,
  onCloseFocus: () => true,
}

export function someBuilder(props) {
   const withDefaults = { ...defaults, ...props }

  function someAutoFocusThing() {
    const falback = onOpenFocus()
    if (fallback) {
      // do our default autofocus behavior
   }
}
```

```svelte
<script lang="ts">
  import { createDropdownMenu } from '@melt-ui/svelte'
  let openFocusEl: HTMLElement | undefined = undefined
  let closeFocusEl: HTMLElement | undefined = undefined

  const { /* ... */ } = createDropdownMenu({
   onOpenFocus: () => {
     if (openFocusEl) {
       openFocusEl.focus()
    } else {
      return true
   }
   },
  onCloseFocus: () => {
     if (closeFocusEl) {
       closeFocusEl.focus()
    } else {
       return true
     }
   }
 })
</script>


<button bind:this={openFocusEl}>
  Focus me on open
</button>
<!-- menu stuff... -->
<button bind:this={closeFocusEl}>
  Focus me on close
</button>
```

In this one, we the user returns the focus target from the function, which seems a bit meh to me considering the logic may exist elsewhere, or you don't want to fallback for one reason or another. Maybe if `undefined` is returned we fall back, and if `false` are returned we don't? 

My brain is having a hard time coming up with something clean at, but curious to hear thoughts from others like @TGlide, as I'm finding myself needing this functionality as well!

```svelte
<script lang="ts">
  import { createDropdownMenu } from '@melt-ui/svelte'
  let openFocusEl: HTMLElement | undefined = undefined

  const { /* ... */ } = createDropdownMenu({
   onOpenFocus: () => {
   // if openFocusEl exists, we'll focus it, otherwise fallback to the default behavior
    return openFocusEl
   },
  onCloseFocus: () => {
     // we don't want to fallback, maybe we're handling the focus some other way outside of this comp.
     return false
   }
 })
</script>


<button bind:this={openFocusEl}>
  Focus me on open
</button>
<!-- menu stuff... -->
```

**Comment by TGlide** [comment]
I've discussed with @huntabyte privately as well, but just so it's out in the open, this is what I propose.

```ts
// $lib/helpers/focus.ts

type FocusTarget = string | HTMLElement | null

export type FocusProp = FocusTarget | (defaultEl?: HTMLElement) => FocusTarget

type HandleFocusArgs = {
	prop?: FocusProp;
	defaultEl?: HTMLElement;
}

export const handleFocus = ({prop, defaultEl}?: HandleFocusArgs = {}) => {
	if (prop === undefined) {
		defaultEl?.focus();
		return;
	}

	const returned = isFunction(prop) ? prop(defaultEl) : prop;

	if (typeof returned === 'string') {
		// Get selector, focus it, early return 
	}
	
	if (isHTMLElement(returned)) {
		// Focus it, early return 
	}
}
```

This basically means, if the focusProp is:
- `null`, no element is focused.
- a function that returns `null `or `undefined`, no element is focused.
- `undefined`, the defaultElement is focused.
- a `string` or `HTMLElement`, or a function that returns those, that gets focused

**Comment by huntabyte** [comment]
Love this solution @TGlide!

**Comment by jzillmann** [comment]
So this should now enabled through https://github.com/melt-ui/melt-ui/pull/663, no ? Trying it out on `Popover` but for some reason `openFocus` isn't get called...

**Comment by TGlide** [comment]
> So this should now enabled through #663, no ? Trying it out on `Popover` but for some reason `openFocus` isn't get called...

Please open an issue if that's the case 😄
