### ISSUE TITLE
🐛Bug: Select initial option not shown in selectedLabel

### ISSUE THREAD

**Issue by lab-do** [melt-ui/melt-ui#637]
**Describe the bug**
The value passed to `defaultSelected` in `createSelect` does not show in the `selectedLabel` state.

**Comment by ZerdoX-x** [comment]
https://github.com/melt-ui/melt-ui/tree/develop/src/lib/builders/select last commit changing this builder was 3 weeks ago; no pr mentions this issue; changelog doesn't mention this issue or anything related to `defaultSelected`. may I know how this issue was fixed? I guess this is not the bug and I am just using API wrong. There are now examples of `defaultSelected` usage, so I am not sure how to fix this myself yet.

**Comment by ZerdoX-x** [comment]
Got it. Instead of `defaultSelected: "foo"` use `defaultSelected: { label: "foo", value: "foo" }`
