### ISSUE TITLE
🐛Bug: Listbox elements should get `data-highlighted` on mouseover

### ISSUE THREAD

**Issue by huntabyte** [melt-ui/melt-ui#667]
**Describe the bug**

Without it, things like this can happen which are not pleasant. I'd like to be able to style using a single selector, regardless if it's highlighted via mouse or via keyboard, and have only one element be `highlighted` at a given time. Basically a single source of truth for where I'm at regardless of what device I'm using (keyboard/mouse).

Hover styles can still be used in addition to this if one would like 😃

https://github.com/melt-ui/melt-ui/assets/64506580/c0c6866c-50b0-4fe2-8957-666cbb955892

**Comment by TGlide** [comment]
I don't think this should be the case, especially since it limits flexibility. You can see that currently, we closely resemble the APG pattern:

https://github.com/melt-ui/melt-ui/assets/26071571/cf532712-958d-4a13-8eee-048443e52517

The focus is always on the trigger. There is a keyboard highlighted item, and there's a separate hovered item.

**Comment by TGlide** [comment]
> Okay yeah that's cool for the examples. Anyone can still apply a different `hover` class and get the same effect, whereas if you _don't_ want that double highlighted effect there's no way around it currently since that source of truth is managed internal to the builder.

We can export the highlightedItem from the builders. That way they can set it on mouse over
