### ISSUE TITLE
🌟Feature request: popover allow no focus on open

### ISSUE THREAD

**Issue by geerew** [melt-ui/melt-ui#71]
**Is your feature request related to a problem? Please describe.**

When a popover opens, the first focusable item is focused. If you style this with , for example, a ring. Then a ring will appear on the first item

if you then use your mouse to over over other elements, such as a button, that for example, have a background colour on hover, you end up with 2 elements that look active leading to confusion as to which element will be triggered if I press enter

see an example here https://stackblitz.com/edit/node-kumaq4?file=src%2Froutes%2F%2Bpage.svelte

**Describe the solution you'd like**

there should be a means to prevent focus on open and close

**Describe alternatives you've considered**
N/a

**Additional context**
N/a

**Comment by huntabyte** [comment]
This seems like more of a styling/CSS selector issue than an issue with a focus on open.

I disagree with the idea to expose a disable autofocus option as a workaround for CSS selector issues. I think a better alternative would be to enable the user to provide a function called when it opens/is focused so that they can do things within, such as change the focused element. But just having nothing be focused on a dialog open (not even a close button) seems wrong.

Reference: https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/

**Comment by TGlide** [comment]
Agree with @huntabyte. We could pass a prop that chooses what the first focused el is, but no focus doesn't make much sense with a Popovers and Dialogs.

Closing, but feel free to discuss more!

**Comment by TGlide** [comment]
Reopening this as I was wrong about this approach. Popovers can be considered non-modal dialogs IMO, in which focus does not have to be trapped: https://accessuse.eu/en/non-modal-dialogs.html

Will be re-acessing how to rework the Popover to reflect this.
