### ISSUE TITLE
🌟Feature request: use floating-ui as peer dependency

### ISSUE THREAD

**Issue by macmillen** [melt-ui/melt-ui#753]
**Is your feature request related to a problem? Please describe.**
I am using floating-ui in my project already and would like to avoid shipping it twice because it comes with melt already. 

**Describe the solution you'd like**
Use floating-ui as a peer dependency.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by huntabyte** [comment]
Can you confirm that it's actually shipping twice?

**Comment by macmillen** [comment]
Actually you're right, it's not shipping twice if it's the same version. But wouldn't it still be cleaner to have it as a peer dependency?

**Comment by TGlide** [comment]
I haven't messed with peerDeps, but from what I've seen, deps are for something your library **needs** to function, while peerDeps are something that is used alongside it. Since we directly need floating UI for our functionality, it seems a dep is better.

Source: https://stackoverflow.com/questions/18875674/whats-the-difference-between-dependencies-devdependencies-and-peerdependencie

Will be closing this now, but we can still discuss 🙂
