### ISSUE TITLE
🐛Bug: Hidden attribute is easily overloaded

### ISSUE THREAD

**Issue by TGlide** [melt-ui/melt-ui#78]
Currently the hidden attribute can be easily overloaded by adding CSS that changes the display property. 

To remedy, there are a few alternatives:
1. Pass in `style: "display: none"` to elements. **Problem:** Large HTML
2. Inject global CSS where `[hidden] {display: none !important}` **Problem:** Not SSRable without extra config
4. A mix of both. On server, pass in style to element. On browser, inject global CSS.

**Comment by huntabyte** [comment]
I agree that the hidden attribute is weak and will cause a lot of issues for peeps. The difference I see in the other 'popper' components vs the dialog is that it's the only one that has the 'hidden' attribute but not 'display: none' which is why it's causing some issues.

I think if global CSS injection is in the route I'm not sure about overriding the [hidden] attribute in case of UIs already built around its flaws.

We could instead use a data attribute and try to keep it consistent throughout all the components that have an open/closed state.

**Comment by huntabyte** [comment]
I think passing the style is the most straightforward approach for the time being.

I only meant adding the data attribute if we were doing a global injection, as we wouldn't want to break anything that's currently hidden and overloaded with a display property somewhere else in the app! This would let us just `!important` the specific melt builder components that we want to control the behavior of!

**Comment by huntabyte** [comment]
Closed by #234
