### ISSUE TITLE
🐛Bug: Toggle Group is not keyboard-focusable when type is 'single'

### ISSUE THREAD

**Issue by mcmxcdev** [melt-ui/melt-ui#810]
**Describe the bug**

I noticed that `tabindex` is set to `-1` initially for all buttons when used as part of Toggle Group with `type: 'single'` while `type: 'multiple'` seems to work fine.

**To Reproduce**

I was able to reproduce the issue on https://stackblitz.com/edit/melt-ui-playground-bfca4r?file=package.json

Note that once you have clicked one of the buttons, it works fine. On initial page load though, all 3 buttons will have tabindex=-1

**Expected behavior**
Expect Toggle Group to be usable with keyboard only.

**Comment by ollema** [comment]
code wise it's quite clear why this happens:
https://github.com/melt-ui/melt-ui/blob/develop/src/lib/builders/toggle-group/create.ts#L81C16-L81C23

but I wonder what the actual expected behaviour is? I can't find any resources online

my guess would be that a user expects that if you press tab you would end up focusing the first element in the toggle group, regardless of pressed/checked status. then from there it's arrow keys to navigate back and forth and tab would focus the next element outside of the group again.

I could attempt to implement a fix if there is a consensus on how tab navigation should be handled

**Comment by mcmxcdev** [comment]
> my guess would be that a user expects that if you press tab you would end up focusing the first element in the toggle group, regardless of pressed/checked status. then from there it's arrow keys to navigate back and forth and tab would focus the next element outside of the group again.

Yeah correct, that's what I would expect at least.

**Comment by huntabyte** [comment]
Yeah this is a bug, it should focus the first one if no values are selected.
