### ISSUE TITLE
Tooltip doesn't work on iPhone

### ISSUE THREAD

**Issue by fromaline** [melt-ui/melt-ui#927]
### Describe the bug

@TGlide, hi!

It seems like the tooltip doesn't work on iPhone even on the melt-ui website.

### Reproduction

It's reproducible even on the melt-ui website — https://melt-ui.com/docs/builders/tooltip.

https://github.com/melt-ui/melt-ui/assets/55146773/e6744ec6-b1e6-4f47-bfba-dc148956d33a

### System Info

```bash
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 950.44 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.3.0 - ~/.nvm/versions/node/v20.3.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.3.0/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v20.3.0/bin/npm
    bun: 1.0.7 - ~/.bun/bin/bun
  Browsers:
    Chrome: 120.0.6099.234
    Safari: 17.2.1
  npmPackages:
    @melt-ui/svelte: ^0.70.0 => 0.70.0 
    @sveltejs/kit: ^1.20.4 => 1.30.3 
    svelte: ^4.0.5 => 4.2.8
```

### Severity

annoyance

**Comment by huntabyte** [comment]
This is expected behavior. See https://github.com/melt-ui/melt-ui/issues/196 for more info regarding this.

**Comment by fromaline** [comment]
@huntabyte, hi! Thanks for the clarification. I'm learning more and more about accessibility thanks to melt-ui.
This behavior definitely should be specified in melt-ui docs. It's super unintuitive unless you're an accessibility geek.

Does setting `closeOnPointerDown` to `false` still work? It seems like not.

**Comment by TGlide** [comment]
> @huntabyte, hi! Thanks for the clarification. I'm learning more and more about accessibility thanks to melt-ui. This behavior definitely should be specified in melt-ui docs. It's super unintuitive unless you're an accessibility geek.
> 
> Does setting `closeOnPointerDown` to `false` still work? It seems like not.

We have this on the docs:
<img width="894" alt="Screenshot 2024-01-22 at 17 18 29" src="https://github.com/melt-ui/melt-ui/assets/26071571/2c50a9f5-3ff7-4a71-9ba6-974f4f0a681e">

I was talking to Hunter though, and I thought it should work due to focus, and it does work on Android. But maybe iPhone just doesn't focus on the button for some reason, or it's a bug on our end. I'll reopen to investigate!

Nonetheless, you're probably better off using a popover on mobile, if you desperately need to show content on press

**Comment by fromaline** [comment]
Oh, it's way down in the accessibility section. My bad, I've never scrolled this far. Just a personal opinion: I'd put this right in the features section.

Yep, maybe it's an iPhone-specific problem. Thanks for the investigation!

I got your point about a popover, thanks! I'll give it a try.

**Comment by huntabyte** [comment]
For future peeps (gonna send this issue now when it's brought up in the time between us documenting this):

As @TGlide mentioned, on certain devices it may focus, but that's only after a `click` has already occurred, meaning the potential context needed to know if you should even click this button isn't displayed until after a click (which is unexpected behavior IMO).

Tooltips are meant to provide _additional_, ***not necessary*** info about a given action (hence the "tip" in the name). If you find yourself needing a tooltip on mobile, you're likely using the wrong tool for the job, and should instead look at a `Popover` or include the contents of the tooltip somewhere else if that content is critical for the user to see.

Here's a great article from a much smarter individual than myself that goes into a bit more detail about this:
[Tooltips in the time of WCAG 2.1](https://arc.net/l/quote/gdrkepxb)

**Comment by fromaline** [comment]
@TGlide, @huntabyte, btw, do you have a roadmap for the melt-ui? Or at least some overview of plans? I'm using the library in production, so it'd be nice to understand where the project is heading.

**Comment by TGlide** [comment]
> @TGlide, @huntabyte, btw, do you have a roadmap for the melt-ui? Or at least some sketchy plans? I'm using the library in production, so it'd be nice to understand where the project is heading.

Nothing super laid out. You'll find most of our plans here in issues, discussions, and sometimes in the Discord. RN the focus is getting 1.0 up and running. That means a focus on stability, fixes, testing, docs, etc.

**Comment by fromaline** [comment]
@TGlide, got it, thanks! I love you project ❤️

**Comment by fromaline** [comment]
I tried using `Popover` on mobile and `Tooltip` on desktop. It 100% works but adds so much complexity to the code, affecting DX.

I'm not that into accessibility and don't know a lot of nuances, but from the info you provided, it's clear that tooltips should work on touch devices.

> Tooltips should only ever contain non-essential content. The best approach to writing tooltip content is to always assume it may never be read.

I don't see any contradictions between the above statement and a functional tooltip on mobile. The content is non-essential anyway. It doesn't matter whether you're on a touch device or a desktop/laptop.

But maybe it's only my naive opinion.

**Comment by TGlide** [comment]
> I tried using Popover on mobile and Tooltip on desktop. It 100% works but adds so much complexity to the code, affecting DX.

Popover an Tooltip usage is not entirely interchangeable. A tooltip servers to provide `a tip regarding a tool`. So it should be used on an interactable element that does something else beside show that tooltip. A popover's trigger however, servers only to open the popover's contents, nothing else.

From [MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tooltip_role):

> The tooltip is not the appropriate role for the more information "i" icon, ⓘ. A tooltip is directly associated with the owning element. The ⓘ isn't 'described by' detailed information; the tool or control is.

---

> it's clear that tooltips should work on touch devices

How so? I only mentioned that when `closeOnPointerDown` is set to `false`, that clicking on the tooltip's trigger won't close it, which does make it work on mobile devices **_if_** they focus elements on click, which it seems iPhone does not do (something we need to investigate though).

It makes sense for tooltips to *not* work on mobile, however. If the only way you can access it on mobile, is by tapping, and that button serves another purpose besides showing the tooltip (which it should by my previous definitions), then once you're shown the information regarding the action, it's already too late, that action already executed!


You can see more of our thoughts here: https://github.com/melt-ui/melt-ui/issues/196

**Comment by fromaline** [comment]
> So it should be used on an interactable element that does something else beside show that tooltip. A popover's trigger however, servers only to open the popover's contents, nothing else.

Wow, I didn't know that at all! With this new info, I understand your points much better. I've been using tooltips wrong my entire life.

So, if I want to show non-critical info user hovers over an "i" icon, I should use Popover instead of Tooltip?

> it's clear that tooltips should work on touch devices

I was wrong, sorry.

**Comment by TGlide** [comment]
> So, if I want to show non-critical info user hovers over an "i" icon, I should use Popover instead of Tooltip?

Yes, but it shouldn't be on hover, rather, on click. Some info here: https://inclusive-components.design/tooltips-toggletips/

**Comment by ivands** [comment]
I don't get why we are taking a hard stance on stuff like this just because someone once made a blog post about tooltips being bad on mobile.
UI design changes daily, and everyone's use case is different.
Simply said, There are legitimate use cases for tooltips working on mobile.
It's up to the developer to implement best practices or move away from them where needed.
There never is a one-size-fits-all solution.
That's also the whole point of shadcn/ui.
To give the developer more control.

**Comment by TGlide** [comment]
> I don't get why we are taking a hard stance on stuff like this just because someone once made a blog post about tooltips being bad on mobile. 

@ivands If you've taken the time to read our discussions for this, such as what we mentioned on #196, you'd know that it's **not** just one blog post, we and several accessibility experts have done **tons** of research, and we **do** provide alternatives for making the tooltip work on mobile, otherwise this issue would have been closed already.

It may just be that this issue doesn't have a solution, in case iPhone does not focus items on click, in which case, I'll leave it as is. If you want to know why, take the time to read our previous explanations on the matter.

> There are legitimate use cases for tooltips working on mobile

Give me one, and how you would like for the user to interact with said tooltip in said case, and we can discuss. 

> That's also the whole point of shadcn/ui.
To give the developer more control.

This is not `shadcn/ui`, it's Melt UI. The point of Melt UI is to give sensible, accessible defaults, while giving you the flexibility to override it however you want. Since we believe there is no sensible or accessible default for tooltips in mobile, we don't include it, but you have the flexibility to implement whatever behaviour you want. So in that sense, you do have control.

**Comment by ivands** [comment]
But I'm trying to build an admin panel with shadcn-svelte.
And I was redirected here after opening an issue about this in bits-ui.
https://github.com/huntabyte/bits-ui/issues/314
My issue was closed because "tooltips should only open on hover" apparently.
This might be the current recommendation from "several accessibility experts."
But why would that recommendation limit the functionality of the API?
It just makes sense to have tooltips work on mobile with a click event or something else.

> Give me one, and how you would like for the user to interact with said tooltip in said case, and we can discuss.

I have hidden information inside the tooltip that is relevant on mobile.

> This is not shadcn/ui, it's Melt UI. The point of Melt UI is to give sensible, accessible defaults, while giving you the flexibility to override it however you want. Since we believe there is no sensible or accessible default for tooltips in mobile, we don't include it, but you have the flexibility to implement whatever behaviour you want. So in that sense, you do have control.

Sorry, I might be in the wrong place.
Yeaaaa should probably be discussing this at bits-ui.

**Comment by TGlide** [comment]
> I'm trying to build an admin panel with shadcn-svelte. And I was redirected here after opening an issue about this in bits-ui.

Yes, I understand.

> My issue was closed because "tooltips should only open on hover" apparently. This might be the current recommendation from "several accessibility experts." But why would that recommendation limit the functionality of the API? 

Because we are working with accessibility in mind, it's the default. Mind you, the original `shadcn/ui` is even stricter than we are in terms of tooltips.

> It just makes sense to have tooltips work on mobile with a click event or something else.

It does not. A tooltip describes a button's action, if you click the button, it'll do the action anyways, you no longer need that tip. Use a popover if you want it on click.


> I have hidden information inside the tooltip that is relevant on mobile.

That does not bring up much for discussion. Why are you hiding it? Why can't you use a popover? How relevant is it? A lot of the times we need to force us to redesign our solutions to better meet users needs. 

> Sorry, I might be in the wrong place. Yeaaaa should probably be discussing this at bits-ui.

I mean, bits behaviour is largely defined by Melt. Unless @huntabyte wants to address adding extra behaviour on top of tooltip over in bits instead of doing it in Melt (which I doubt), this is the right place. In any case, I mentioned the distinction to share what my vision is for this project.

**Comment by ivands** [comment]
Sorry, let me be more descriptive about my use case:
I have a bar graph with multiple data points inside a single X-axis.
When you hover over a bar, you get a summary of all the data on that axis.
It makes sense to be still able to show the summary on mobile when you press the bar.
In my use case, the hover event is more desirable on desktop, and the click event is our only option on mobile.

**Comment by TGlide** [comment]
> Sorry, let me be more descriptive about my use case: I have a bar graph with multiple data points inside a single X-axis. When you hover over a bar, you get a summary of all the data on that axis. It makes sense to be still able to show the summary on mobile when you press the bar. In my use case, the hover event is more desirable on desktop, and the click event is our only option on mobile.

Probably not the best case for a tooltip. As the name says, a tooltip is a *tip* that describes a *tool*. Sorry to be nitpicky about naming, but it does matter, a lot of other considerations come into tooltips besides cursor, such as aria-roles, keyboard interactivity, etc. In your case, I'd probably use floating-ui directly for something more custom.

**Comment by ivands** [comment]
Yeah, I was using floating-ui before. I'm making V2 of our service right now. So I was hoping I don't have to make everything myself again. XD
Guess there is no way around it.

**Comment by TGlide** [comment]
> This has to be some meme or something. You start a project hoping there is a UI library that can fulfill your needs. But it always turns out you need some custom functionality, and now you have to make it yourself.

Such is life! But tbh it's okay if a UI library doesn't fill your needs 100%. That's what's nice about headless, take what you need and scrap the rest. It doesn't affect the rest of your app.

**Comment by shellicar** [comment]
So what about the scenario where you want something to trigger on hover (mouse) OR click (touch)?

The shadcn-svelte documentation [https://www.shadcn-svelte.com/docs/components/tooltip](https://www.shadcn-svelte.com/docs/components/tooltip) says:

> Provides additional information or context when users hover over or interact with an element.

Last I checked clicking on something is interacting.

> That does not bring up much for discussion. Why are you hiding it? Why can't you use a popover? How relevant is it? A lot of the times we need to force us to redesign our solutions to better meet users needs.

I understand the desire to make things accessible by default, but there's a reason everyone expects it to work this way.

I don't understand why using a component with a different name is considered the solution.
Is it because of the name? I pick a component based on the behaviour I want and expect. Is a popover magically more accessible than a Tooltip?

Additionally, tooltips do not have to be attached to buttons that perform an immediate action. It can be attached to any GUI element which could require more context. Triggering from hover on desktop and clicking on mobile (or long pressing) is the obvious and intuitive way to display this information.

**Comment by TGlide** [comment]
> So what about the scenario where you want something to trigger on hover (mouse) OR click (touch)?

Tooltip is not intended for this.

> The shadcn-svelte documentation says

Sorry, but that's not relevant. Melt's documentation is the important bit here.

> Is it because of the name? I pick a component based on the behaviour I want and expect. 

Of course it's not because of the name. They have different behaviours, accessibility concerns, etc. E.g. a popover can have interactible content inside it, a tooltip cannot.

> Is a popover magically more accessible than a Tooltip?

No such thing, it's just more suitable in certain situations. 

> is the obvious and intuitive way to display this information.

Obvious to whom? Will screen readers say that you should long press it? Is there a consensus to have tooltips on any button? You **need** to hover a button before clicking it, so a tooltip naturally appearing is a nice bonus. And tooltips generally work this way. 

Long pressing does not necessarily bring tooltips in other places. It's not a standard in any shape or form. 

Being a UI library, the choices we make greatly impact the web, specially as it grows. We can't be careless and assume, things need to be done with a lot of thought, evidence, and study.
