### ISSUE TITLE
🌟Feature request: introduce Checkbox Group builder

### ISSUE THREAD

**Issue by mcmxcdev** [melt-ui/melt-ui#942]
**Is your feature request related to a problem? Please describe.**
In the docs there is a showcase for a single checkbox, e.g. https://melt-ui.com/docs/builders/checkbox

Since checkboxes are usually used in multiples, see https://www.w3schools.com/tags/att_input_type_checkbox.asp, it leaves me wondering why the docs show no example with multiple selections. Essentially, if there would be a Checkbox Group same like there is a Radio Group that would be great and save every developer time reinventing the wheel there.

**Describe the solution you'd like**
Add Checkbox Group builder which supports multiple selection.

**Describe alternatives you've considered**
Use Checkbox builder and hope that I can loop over it and modify to my needs as expected.

**Comment by TGlide** [comment]
Radio group exists because you can only select one from a group. Checkboxes have no such restriction. We could add an example of how to loop over these items in an efficient manner, but I don't believe there is need for a checkbox group anymore than we need something like a select group. 

We also added radio group because of the APG pattern.

Will close this :)
